services:
  api_db:
    image: postgres
    env_file:
      - ./api/.env
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_EXTERN}:${DB_PORT}"

  api:
    container_name: poll-api
    build:
      context: ./api/
    env_file:
      - ./api/.env
    depends_on:
      - api_db
    ports:
      - "${API_PORT}:${API_PORT}"

  front:
    container_name: poll-front
    build:
      context: ./front/
    depends_on:
      - api
